### ISSUE TITLE
2. Tetris Grid

### ISSUE THREAD

**Issue by nsafai** [MakeSchool-Tutorials/web-7-react-redux-tetris-app#2] opened 2019-04-04 18:52 UTC
Couple small typos:

(1) `.App-header {}` styles are in `App.css` not `index.css`

(2)
`import Gridsquare from './components/grid-square'` should be `import GridSquare from './components/grid-square'`

**Comment by LucHighwalker** [comment] 2019-04-04 19:05
Beat you to it :P

**Comment by soggybag** [comment] 2019-04-07 04:28
Can you post the page and topic heading where this is? You can also comment on the line of code on GitHub.

**Comment by ibirnam** [comment] 2019-04-08 15:53
@nsafai 
- css fixed in 7d66f7ddeefe1d6f2f58222e95c32142a52b6b97
- import fixed in 454070f0849bb0390a952aa68f02c8c434de8eac

Agree with Mitchell that putting in chapter+topic heading is super helpful for figuring out where exactly the issue is. Please do this in the future!

**Closed as completed by ibirnam** 2019-04-08 15:53 UTC
